### PR TITLE
Ignore mix.lock file

### PR DESCRIPTION
**Pull request by kianmeng**

### CODE REVIEW

**Comment by devstopfix** [comment]
@kianmeng what is your reason for this? Was there an error?  From the docs

> Mix will lock the version of a dependency in the lockfile to ensure that all developers will get the same version (always commit mix.lock to version control).

https://hex.pm/docs/usage

**Comment by kianmeng** [comment]
@devstopfix I'm under the impression that the `mix.lock` file was not added to the repo was intentional. Some Elixir module developers prefer this approach but just ignore the `mix.lock` file.

Hence, this PR was created to ignore `mix.lock` to prevent accidental commit by others to the repo as it's marked as untracked file by git.

Perhaps as the doc suggested, we can commit the `mix.lock` file to the repo so we all can have the same version?

```
$ git clone https://github.com/devstopfix/gnuplot-elixir.git
$ mix deps.get
$ git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        mix.lock

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by devstopfix** [comment]
Ah! I removed it by accident - I will put it back 🙈

**Comment by devstopfix** [comment]
Thanks for spotting this - my global gitignore somehow had mix.lock in it 🤷‍♂️

**Pull request closed without merging**
