### PR TITLE
Misc doc changes

### PR DESCRIPTION
**Pull request by kianmeng**
List of changes:

- Use common source url
- Set readme as default html page
- Put all image assets to default folder
- Badges and more badges!
- Rename assets filename
- Revise installation note
- Update example script to output lower case file extension

### CODE REVIEW

**Comment by devstopfix** [comment]
Thanks! I will take a look later

**Comment by devstopfix** [comment]
@kianmeng can we leave the sample images in docs? Moving them to assets implies to me that they will be delivered in the hex package. Also - changing the case of the extension can be a bit of a pain

**Comment by kianmeng** [comment]
> @kianmeng can we leave the sample images in docs? Moving them to assets implies to me that they will be delivered in the hex package. Also - changing the case of the extension can be a bit of a pain

@devstopfix In what ways the sample images are added to the hex package? See the `Files` section below which doesn't includes the file.

```
$ mix hex.build
Building gnuplot 1.20.320
  Dependencies:
    ex_doc ~> 0.23.0 (app: ex_doc)
  App: gnuplot
  Name: gnuplot
  Files:
    lib
    lib/gnuplot
    lib/gnuplot/bin.ex
    lib/gnuplot/dataset.ex
    lib/gnuplot/commands.ex
    lib/gnuplot.ex
    mix.exs
    README.md
    LICENSE
  Version: 1.20.320
  Build tools: mix
  Description: Interface between Elixir and Gnuplot graphing library
  Licenses: EPL-2.0
  Links: 
    GitHub: https://github.com/devstopfix/gnuplot-elixir
    Gnuplot: http://www.gnuplot.info/
    Travis CI: https://travis-ci.org/devstopfix/gnuplot-elixir
  Elixir: ~> 1.7
Package checksum: d0d34ee3773d5be7827938d8ab63b64efafa2ac6e56cf354a2888f6ad95c303b
Saved to gnuplot-1.20.320.tar

```

Moving it to assets folder so it won't be confused with the output `doc` folder and [following the recommendation](https://hexdocs.pm/ex_doc/Mix.Tasks.Docs.html#module-configuration).
> :assets - Path to a directory that will be copied as is to the "assets" directory in the output path. Its entries may be referenced in your docs under "assets/ASSET.EXTENSION"; defaults to no assets directory.

Changing the case of the extension of the output images from the script in the `examples` folder is due to this error.

```
$ mix docs
Generating docs...
...

** (RuntimeError) asset with extension ".PNG" is not supported by EPUB format
    (ex_doc 0.23.0) lib/ex_doc/formatter/epub/templates.ex:131: ExDoc.Formatter.EPUB.Templates.media_type/1
    (ex_doc 0.23.0) lib/ex_doc/formatter/epub/templates/content_template.eex:31: anonymous fn/2 in ExDoc.Formatter.EPUB.Templates.content_template/5
    (elixir 1.11.1) lib/enum.ex:2181: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ex_doc 0.23.0) lib/ex_doc/formatter/epub/templates/content_template.eex:30: ExDoc.Formatter.EPUB.Templates.content_template/5
    (ex_doc 0.23.0) lib/ex_doc/formatter/epub.ex:81: ExDoc.Formatter.EPUB.generate_content/5
    (ex_doc 0.23.0) lib/ex_doc/formatter/epub.ex:36: ExDoc.Formatter.EPUB.run/2
    (ex_doc 0.23.0) lib/mix/tasks/docs.ex:349: anonymous fn/6 in Mix.Tasks.Docs.run/3
    (elixir 1.11.1) lib/enum.ex:2181: Enum."-reduce/3-lists^foldl/2-0-"/3
```

I've also updated the script in `examples` folder to output image in lowercase file extension.

**Comment by devstopfix** [comment]
OK i misunderstood the purpose of this commit - "misc doc changes" implied housekeeping to me. This commit is actually changing 'mix doc' to generate more comprehensive docs. I didn't know this was possible

**Pull request merged**
